### ISSUE TITLE
Pass shortcut through

### ISSUE THREAD

**Issue by amlwwalker** [falceeffect/UGlobalHotkey#14]
Hi, I realise you are not too active on this, but I was wondering if it is possible to pass the short cut through to the window that has focus after dealing with it. Would be cool to for instance do something when a user presses Ctrl+S (save) and it still saves the application while intercepting and doing something with it
Is this possible?

**Comment by falceeffect** [comment]
Hello!

The library provides a functionality to set **global** (i. e. system-wide hotkeys, as in `PrtScr` triggering you favorite screenshot utility). It was not really intended to be used as an in-application hotkey manager, as this functionality is implemented in Qt itself.

As far as I understood, you want to pass hotkeys from some modal window to the main application window, am I right? In this case UGlobalHotkeys should _technically_ work (as it sets system-wide hotkeys), but not exactly as you intend it to. By that I mean that **all** of `Ctrl-S` presses in system will trigger the "Save" action as long as your application is still running. Otherwise, I don't think there is a way to do what you want with UGlobalHotkey.

I guess you could try subclassing the modal window class you use and implement the pass through by hand.

**Comment by amlwwalker** [comment]
Hello, thanks for getting back to me!

Ok, I'm not sure if what you say is solving my problem or I have just confused the matter...

So I have a small app using this, that when someone presses Cmd+S, it will show me "activated 2" - 2 because its the second shortcut I setup (I know, could be better UX!)

I have an unsaved document, in focus (the foreground) that should save when I press Cmd+S:

![image](https://user-images.githubusercontent.com/2920180/66394365-d6ed8000-e9cc-11e9-886f-9546194cf981.png)

The issue I have, is that now my little app using this library is running, even though its in the background (not in focus) it captures/hijacks the Cmd+S and the document in focus doesnt save.

I am wondering how I can still let the document in the foreground save AND my little app will notice that Cmd+S was saved, i.e not hijack the Cmd+S entirely....
Does that make sense, was that what you understood me to mean?

Thanks again

**Comment by falceeffect** [comment]
Oh, I thought that the second ("overlapping") window you were talking about belonged to your application as well. But now I see what you mean. 

I actually don't know if it's possible to modify the library in order to support the behavior you want. It might be possible, but I don't really have enough knowledge of system-level APIs to implement that :(
It might be enough to "push the event further down the system pipeline" or something like that, but I'm not sure. This is hard because every system (i. e. X11, Windows, OS X) has its own API.

**Comment by amlwwalker** [comment]
Interesting, so when you globally register a short cut, the OS hands it to you... thats strange. It's like a weird hack - Install a bit of malware on computers, hijacking all the shortcuts so nothing can do anything 😂
